version: "3"
services:

  judge-server:
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
    container_name: judge-server
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/testCase:/test_case:ro
      - ./data/judgeServer/log:/log
      - ./data/judgeServer/run:/judger
    environment:
      # 修改SERVICE_URL
      - SERVICE_URL=http://127.0.0.1:8080
      # 修改BACKEND_URL
      - BACKEND_URL=http://192.168.1.158:8090/OnlineJudge/judgeServer/judge_server_heartbeat/
      # TOKEN和运行后端时设置的TOKEN相同
      - TOKEN=TOKEN
      # - judger_debug=1
    ports:
      - "0.0.0.0:7777:8080"