spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.214.134:5432/onlinejudge
    username: zi
    password: 6009309
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
  #  mail:
  #    host: smtp.163.com
  #    username: XMUT_OnlineJudge@163.com
  #    password: HMWEBWRGIZWSLQDG
  #    properties:
  #      mail:
  #        smtp:
  #          starttls:
  #            enable: true
  #            required: true
  redis:
    # 连接地址
    host: "localhost"
    # 端口
    port: 6379
    # 数据库
    database: 0
    # 用户名，如果有
    # username:
    # 密码，如果有
    # password:
    # 连接超时
    connect-timeout: 5s
    # 读超时
    timeout: 5s

mybatis-flex:
  mapper-locations:
    - classpath*:/mapper/*.xml


server:
  port: 8090
  servlet:
    context-path: /OnlineJudge

files:
  upload:
    testCase:
      path: data/public/testCase/
    avatar:
      path: data/public/avatar/



